using System;
using System.Diagnostics;
using System.IO;

namespace PDJaya.Helpers
{
    public class ESCPOS
    {
        static string Print(string cmd, params string[] args)
        {   
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "python";
            start.Arguments = string.Format("\"{0}\"", cmd);
            foreach(var arg in args)
            {
                start.Arguments += string.Format( " \"{0}\"",arg);
            }
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }

        public static string PrintStruct()
        {
            return Print("/home/pi/print/print.py", "");
        }
    }
}
