//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class applog
{
    public long Id { get; set; }
    public string LogID { get; set; }
    public System.DateTime LogDate { get; set; }
    public int LogType { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Source { get; set; }
}

public partial class bill
{
    public long Id { get; set; }
    public string BillID { get; set; }
    public string MarketNo { get; set; }
    public string StoreNo { get; set; }
    public string TransactionCode { get; set; }
    public decimal Amount { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public int Month { get; set; }
    public int Year { get; set; }
    public bool IsPaid { get; set; }
}

public partial class device
{
    public string CreatedBy { get; set; }
    public string UpdatedBy { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Updated { get; set; }
    public long Id { get; set; }
    public string DeviceNo { get; set; }
    public int Status { get; set; }
    public string Remark { get; set; }
    public string Location { get; set; }
    public double Longitude { get; set; }
    public double Latitude { get; set; }
    public System.DateTime PlacementDate { get; set; }
    public string IP { get; set; }
    public string MarketNo { get; set; }
    public int GMTTimeGap { get; set; }
    public double DesignWidth { get; set; }
    public double DesignHeight { get; set; }
    public string ApiScope { get; set; }
    public string ApiKey { get; set; }
    public string ServiceHost { get; set; }
    public string AccessToken { get; set; }
    public string ServiceAuth { get; set; }
    public string PrintFile { get; set; }
    public string GrpcHost { get; set; }
    public Nullable<int> GrpcPort { get; set; }
}

public partial class group
{
    public string CreatedBy { get; set; }
    public string UpdatedBy { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Updated { get; set; }
    public long Id { get; set; }
    public string GroupID { get; set; }
    public string GroupName { get; set; }
}

public partial class market
{
    public string CreatedBy { get; set; }
    public string UpdatedBy { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Updated { get; set; }
    public long Id { get; set; }
    public string MarketNo { get; set; }
    public string MarketName { get; set; }
    public string Address { get; set; }
    public string Remark { get; set; }
    public string Phone { get; set; }
    public double Longitude { get; set; }
    public double Latitude { get; set; }
}

public partial class my_aspnet_applications
{
    public int id { get; set; }
    public string name { get; set; }
    public string description { get; set; }
}

public partial class my_aspnet_membership
{
    public int userId { get; set; }
    public string Email { get; set; }
    public string Comment { get; set; }
    public string Password { get; set; }
    public string PasswordKey { get; set; }
    public Nullable<sbyte> PasswordFormat { get; set; }
    public string PasswordQuestion { get; set; }
    public string PasswordAnswer { get; set; }
    public Nullable<bool> IsApproved { get; set; }
    public Nullable<System.DateTime> LastActivityDate { get; set; }
    public Nullable<System.DateTime> LastLoginDate { get; set; }
    public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
    public Nullable<System.DateTime> CreationDate { get; set; }
    public Nullable<bool> IsLockedOut { get; set; }
    public Nullable<System.DateTime> LastLockedOutDate { get; set; }
    public Nullable<long> FailedPasswordAttemptCount { get; set; }
    public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
    public Nullable<long> FailedPasswordAnswerAttemptCount { get; set; }
    public Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowStart { get; set; }
}

public partial class my_aspnet_paths
{
    public int applicationId { get; set; }
    public string pathId { get; set; }
    public string path { get; set; }
    public string loweredPath { get; set; }
}

public partial class my_aspnet_personalizationallusers
{
    public string pathId { get; set; }
    public byte[] pageSettings { get; set; }
    public System.DateTime lastUpdatedDate { get; set; }
}

public partial class my_aspnet_personalizationperuser
{
    public int id { get; set; }
    public int applicationId { get; set; }
    public string pathId { get; set; }
    public Nullable<int> userId { get; set; }
    public byte[] pageSettings { get; set; }
    public System.DateTime lastUpdatedDate { get; set; }
}

public partial class my_aspnet_profiles
{
    public int userId { get; set; }
    public string valueindex { get; set; }
    public string stringdata { get; set; }
    public byte[] binarydata { get; set; }
    public Nullable<System.DateTime> lastUpdatedDate { get; set; }
}

public partial class my_aspnet_roles
{
    public int id { get; set; }
    public int applicationId { get; set; }
    public string name { get; set; }
}

public partial class my_aspnet_sessioncleanup
{
    public System.DateTime LastRun { get; set; }
    public int IntervalMinutes { get; set; }
    public int ApplicationId { get; set; }
}

public partial class my_aspnet_sessions
{
    public string SessionId { get; set; }
    public int ApplicationId { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Expires { get; set; }
    public System.DateTime LockDate { get; set; }
    public int LockId { get; set; }
    public int Timeout { get; set; }
    public bool Locked { get; set; }
    public byte[] SessionItems { get; set; }
    public int Flags { get; set; }
}

public partial class my_aspnet_sitemap
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Url { get; set; }
    public string Roles { get; set; }
    public Nullable<int> ParentId { get; set; }
}

public partial class my_aspnet_users
{
    public int id { get; set; }
    public int applicationId { get; set; }
    public string name { get; set; }
    public bool isAnonymous { get; set; }
    public Nullable<System.DateTime> lastActivityDate { get; set; }
}

public partial class my_aspnet_usersinroles
{
    public int userId { get; set; }
    public int roleId { get; set; }
}

public partial class payment
{
    public long Id { get; set; }
    public string TransactionID { get; set; }
    public string MarketNo { get; set; }
    public System.DateTime PaymentDate { get; set; }
    public string StoreNo { get; set; }
    public string TransactionName { get; set; }
    public string TransactionCode { get; set; }
    public decimal Amount { get; set; }
    public int Status { get; set; }
    public string CardNo { get; set; }
}

public partial class synclog
{
    public long Id { get; set; }
    public string SyncID { get; set; }
    public System.DateTime SyncDate { get; set; }
    public int Status { get; set; }
    public string Remark { get; set; }
    public string Source { get; set; }
}

public partial class tenant
{
    public string CreatedBy { get; set; }
    public string UpdatedBy { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Updated { get; set; }
    public long Id { get; set; }
    public string StoreNo { get; set; }
    public string Owner { get; set; }
    public string Remark { get; set; }
    public int Status { get; set; }
    public string MarketNo { get; set; }
}

public partial class tenantcard
{
    public string CreatedBy { get; set; }
    public string UpdatedBy { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Updated { get; set; }
    public long Id { get; set; }
    public string CardID { get; set; }
    public string StoreNo { get; set; }
    public string CardNo { get; set; }
    public string CardType { get; set; }
    public int Status { get; set; }
}

public partial class usergroup
{
    public string CreatedBy { get; set; }
    public string UpdatedBy { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Updated { get; set; }
    public long Id { get; set; }
    public long UserId { get; set; }
    public long GroupId { get; set; }
}

public partial class userprofile
{
    public string CreatedBy { get; set; }
    public string UpdatedBy { get; set; }
    public System.DateTime Created { get; set; }
    public System.DateTime Updated { get; set; }
    public long Id { get; set; }
    public string UserId { get; set; }
    public string UserName { get; set; }
    public string FullName { get; set; }
    public string Password { get; set; }
    public string Department { get; set; }
    public string Branch { get; set; }
    public bool IsActive { get; set; }
    public string Firstname { get; set; }
    public string Lastname { get; set; }
    public string Email { get; set; }
    public string Role { get; set; }
    public string Phone { get; set; }
}
