//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PDJayaEntities : DbContext
{
    public PDJayaEntities()
        : base("name=PDJayaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<applog> applogs { get; set; }
    public DbSet<bill> bills { get; set; }
    public DbSet<device> devices { get; set; }
    public DbSet<group> groups { get; set; }
    public DbSet<market> markets { get; set; }
    public DbSet<payment> payments { get; set; }
    public DbSet<synclog> synclogs { get; set; }
    public DbSet<tenantcard> tenantcards { get; set; }
    public DbSet<tenant> tenants { get; set; }
    public DbSet<usergroup> usergroups { get; set; }
    public DbSet<userprofile> userprofiles { get; set; }
    public DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
    public DbSet<my_aspnet_membership> my_aspnet_membership { get; set; }
    public DbSet<my_aspnet_paths> my_aspnet_paths { get; set; }
    public DbSet<my_aspnet_personalizationallusers> my_aspnet_personalizationallusers { get; set; }
    public DbSet<my_aspnet_personalizationperuser> my_aspnet_personalizationperuser { get; set; }
    public DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
    public DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
    public DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
    public DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
    public DbSet<my_aspnet_sitemap> my_aspnet_sitemap { get; set; }
    public DbSet<my_aspnet_users> my_aspnet_users { get; set; }
    public DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
}
